### ISSUE TITLE
Flutter plugin installed but not used is sonar-scanner-cli

### ISSUE THREAD

**Issue by Bogala** [insideapp-oss/sonar-flutter#217] opened 2024-05-02 17:17 UTC
Hello,

Il my analysis with the last version of sonarqube and sonar scanner cli, the scanner doesn't download flutter plugin :
```
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=190ms
INFO: Load active rules
INFO: Load active rules (done) | time=6224ms
INFO: Load analysis cache
INFO: Load analysis cache (404) | time=147ms
INFO: Preprocessing files...
INFO: 1 language detected in 85 preprocessed files
INFO: 0 files ignored because of scm ignore settings
INFO: Loading plugins for detected languages
INFO: Load/download plugins
INFO: Load/download plugins (done) | time=3339ms
INFO: Inconsistent constructor declaration on bean with name 'org.sonarsource.scanner.api.internal.IsolatedClassloader@3e8c3cb-org.sonar.scanner.issue.IssueFilters': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public org.sonar.scanner.issue.IssueFilters(org.sonar.api.batch.fs.internal.DefaultInputProject)
INFO: Load project repositories
INFO: Load project repositories (done) | time=161ms
INFO: Indexing files...
INFO: Project configuration:
INFO:   Excluded sources for coverage: **/*.g.dart
INFO: 85 files indexed
INFO: Quality profile for yaml: Sonar way
INFO: ------------- Run sensors on module Nouvelle application Listo
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=155ms
INFO: Sensor JaCoCo XML Report Importer [jacoco]
INFO: 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
INFO: No report imported, no coverage information will be imported by JaCoCo XML Report Importer
INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=1ms
INFO: Sensor IaC CloudFormation Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC CloudFormation Sensor [iac] (done) | time=17ms
INFO: Sensor IaC Kubernetes Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC Kubernetes Sensor [iac] (done) | time=67ms
INFO: Sensor JavaScript inside YAML analysis [javascript]
INFO: No input files found for analysis
INFO: Hit the cache for 0 out of 0
INFO: Miss the cache for 0 out of 0
INFO: Sensor JavaScript inside YAML analysis [javascript] (done) | time=5ms
INFO: Sensor CSS Rules [javascript]
INFO: No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
INFO: Sensor CSS Rules [javascript] (done) | time=0ms
INFO: Sensor IaC Docker Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC Docker Sensor [iac] (done) | time=44ms
INFO: Sensor TextAndSecretsSensor [text]
INFO: Available processors: 4
INFO: Using 4 threads for analysis.
INFO: 1 source file to be analyzed
INFO: 1/1 source file has been analyzed
```

Can you help me ?

**Comment by ReinhardvdBerg** [comment] 2024-05-08 07:55
I'm also experiencing the same issue after upgrading SQ to v10.5.1, I see there's some mention of updates required to custom plugins in the release notes:
https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/release-upgrade-notes/

**Comment by Bogala** [comment] 2024-05-13 09:59
If I read correctly, we would have to update the dependencies and recompile the sonar-flutter plugin ourselves?

**Comment by zippy1978** [comment] 2024-05-13 12:17
Hi,
This is due to a SonarQube API update. I will try to fix it when I have time.

**Comment by ReinhardvdBerg** [comment] 2024-05-16 12:11
Thanks @zippy1978 it will be much appreciated!

**Comment by zippy1978** [comment] 2024-05-16 16:21
This is a duplicate of https://github.com/insideapp-oss/sonar-flutter/issues/212

**Comment by zippy1978** [comment] 2024-05-16 18:22
Fixed in new release: https://github.com/insideapp-oss/sonar-flutter/releases/tag/0.5.1

**Closed by zippy1978** 2024-05-16 18:22 UTC
Labels: bug, duplicate, fixed on develop
